objs: ["user", "group"]
attrs: ["avatar", "cover"]
classes: ["User", "GroupUser", "Album"]
metas: ["User", "Image"]
search_objects: ["Image", "User", "Group"]
load_more_user_size: 4
load_more_image_size: 4
load_more_comment_size: 3
length_more_user: 4
length_name: 15
length_more_name: 30
limit_depth: 2
length_truncate_description: 45
